spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  session:
    store-type: none
  autoconfigure:
    exclude:
    - org.springframework.boot.data.redis.autoconfigure.DataRedisAutoConfiguration
    - org.springframework.boot.session.data.redis.autoconfigure.SessionDataRedisAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
server:
  servlet:
    session:
      cookie:
        secure: false
