-- V1: 초기 스키마 — users, posts, follows, follow_counts
-- PostgreSQL 대상. H2 호환 구문 사용 (dev 프로필에서도 Flyway 실행 가능).

-- =====================================================
-- 1. users
-- =====================================================
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255)  NOT NULL,
    password       VARCHAR(255)  NOT NULL,
    nickname       VARCHAR(255)  NOT NULL,
    role           VARCHAR(20)   NOT NULL DEFAULT 'USER',
    token_version  INT           NOT NULL DEFAULT 0,

    CONSTRAINT uq_users_email    UNIQUE (email),
    CONSTRAINT uq_users_nickname UNIQUE (nickname)
);

-- =====================================================
-- 2. posts
-- =====================================================
CREATE TABLE posts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id   BIGINT        NOT NULL,  -- users.id (FK 제약 없음)
    content     VARCHAR(500)  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_posts_author_id ON posts (author_id);

-- =====================================================
-- 3. follows (soft delete)
-- =====================================================
CREATE TABLE follows (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id   BIGINT   NOT NULL,  -- users.id (FK 제약 없음)
    following_id  BIGINT   NOT NULL,  -- users.id (FK 제약 없음)
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted       BOOLEAN  NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uq_follows_pair UNIQUE (follower_id, following_id)
);

-- following_id 단독 인덱스 — 팔로워 목록 조회 (UNIQUE 인덱스 미커버)
CREATE INDEX idx_follows_following_id ON follows (following_id);

-- 복합 인덱스 — 팔로워/팔로잉 목록 페이징 최적화
CREATE INDEX idx_follows_following_created ON follows (following_id, created_at DESC);
CREATE INDEX idx_follows_follower_created  ON follows (follower_id, created_at DESC);

-- =====================================================
-- 4. follow_counts (비정규화 카운트)
-- =====================================================
CREATE TABLE follow_counts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,  -- users.id (FK 제약 없음)
    followers_count  BIGINT NOT NULL DEFAULT 0,
    followees_count  BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uq_follow_counts_user_id UNIQUE (user_id)
);
