-- V5: 좋아요(리액션) 테이블 생성

CREATE TABLE post_likes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL,
    post_id     BIGINT        NOT NULL,
    reaction    VARCHAR(20)   NOT NULL DEFAULT 'LIKE',
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at  TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uq_post_likes_user_post UNIQUE (user_id, post_id)
);

CREATE INDEX idx_post_likes_post_id ON post_likes (post_id);
CREATE INDEX idx_post_likes_user_id ON post_likes (user_id);

-- 부분 인덱스 (PostgreSQL) — 활성 좋아요만
CREATE INDEX idx_post_likes_post_active
    ON post_likes (post_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_post_likes_user_active
    ON post_likes (user_id, created_at DESC) WHERE deleted_at IS NULL;
