-- V6: 미디어 테이블 생성

CREATE TABLE media (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_type  VARCHAR(10)   NOT NULL,
    path        VARCHAR(500)  NOT NULL,
    status      VARCHAR(20)   NOT NULL DEFAULT 'INIT',
    user_id     BIGINT        NOT NULL,
    upload_id   VARCHAR(255),
    attributes  TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at  TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_media_user_id ON media (user_id);
CREATE INDEX idx_media_status ON media (status);

-- 정리 배치용: 미완료 상태 + 오래된 항목
CREATE INDEX idx_media_status_created
    ON media (status, created_at)
    WHERE status IN ('INIT', 'UPLOADED');
